In [1]:
import torch

In [5]:
z = torch.zeros((5,3), dtype=torch.float64)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
torch.float64


In [6]:
i = torch.ones((5,3), dtype=torch.int32)
print(i)
print(i.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.int32


In [7]:
torch.manual_seed(20250817)
r1 = torch.rand((2,2), dtype=torch.float64)
print('A random tensor r1:')
print(r1)

r2 = torch.rand((2,2), dtype=torch.float64)
print('\nA differnt random tensor r2:')
print(r2)

torch.manual_seed(20250817)
r3 = torch.rand((2,2), dtype=torch.float64)
print('\nShould match to r1:')
print(r3)


A random tensor r1:
tensor([[0.6796, 0.5319],
        [0.2050, 0.0128]], dtype=torch.float64)

A differnt random tensor r2:
tensor([[0.7765, 0.6283],
        [0.4771, 0.4501]], dtype=torch.float64)

Should match to r1:
tensor([[0.6796, 0.5319],
        [0.2050, 0.0128]], dtype=torch.float64)


In [8]:
ones = torch.ones((2,3), dtype=torch.float64)
print(ones)

twos = torch.ones((2,3), dtype=torch.float64) * 2
print(twos)

threes = ones + twos
print(threes)

r1 = torch.rand((2,3), dtype=torch.float64)
r2 = torch.rand((3,2), dtype=torch.float64)
r3 = r1 + r2

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)
tensor([[3., 3., 3.],
        [3., 3., 3.]], dtype=torch.float64)


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [9]:
r = torch.rand((2,2), dtype=torch.float64) * 2 - 1
print('A random matrix, r:')
print(r)

print('\nAbsolute value of r:')
print(torch.abs(r))

print('\nArc sine of r:')
print(torch.asin(r))

print('\nDeterminant of r:')
print(torch.det(r))
print('\nSingular value decomposition of r:')
print(torch.svd(r))

print('\nAverage and standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))

A random matrix, r:
tensor([[ 0.8943, -0.5938],
        [-0.9522, -0.1208]], dtype=torch.float64)

Absolute value of r:
tensor([[0.8943, 0.5938],
        [0.9522, 0.1208]], dtype=torch.float64)

Arc sine of r:
tensor([[ 1.1068, -0.6358],
        [-1.2603, -0.1211]], dtype=torch.float64)

Determinant of r:
tensor(-0.6735, dtype=torch.float64)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.7572,  0.6532],
        [ 0.6532,  0.7572]], dtype=torch.float64),
S=tensor([1.3510, 0.4985], dtype=torch.float64),
V=tensor([[-0.9616, -0.2744],
        [ 0.2744, -0.9616]], dtype=torch.float64))

Average and standard deviation of r:
(tensor(0.8009, dtype=torch.float64), tensor(-0.1931, dtype=torch.float64))

Maximum value of r:
tensor(0.8943, dtype=torch.float64)


In [11]:

A = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
U, S, V = torch.linalg.svd(A, full_matrices=False)

print("A:", A)
print("U:", U)
print("S:", S)
print("V:", V)



A: tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
U: tensor([[-0.2298,  0.8835],
        [-0.5247,  0.2408],
        [-0.8196, -0.4019]])
S: tensor([9.5255, 0.5143])
V: tensor([[-0.6196, -0.7849],
        [-0.7849,  0.6196]])
